### ISSUE TITLE
OEP5: Approve Wallet Vulnerability

### ISSUE THREAD

**Issue by WyattMufson** [ONT-Avocados/python-template#20]
@tonyclarking @Avocas 

You're not clearing the approved address after a transfer. That means you can:

- Approve yourself
- Transfer the token to someone else (say in an exchange)
- Take ownership back immediately after

**Comment by WyattMufson** [comment]
@Avocas are you going to fix this?

**Comment by Avocas** [comment]
thanks, we had fixed this bug

**Comment by WyattMufson** [comment]
@Avocas... no you didn't

https://github.com/ONT-Avocados/python-template/blob/master/OEP5Sample/OEP5Sample.py#L161

You don't define `approveKey` and the compiler v2 contract hasn't been fixed.

You should leave this open until the bug is fixed.

**Comment by Avocas** [comment]
i'm so sorry, i fix it again.

**Comment by Avocas** [comment]
thanks for your remind

**Comment by WyattMufson** [comment]
Resolved by 0acb503

**Comment by WyattMufson** [comment]
Also worth nothing that you can use `ctx` instead of `GetContext()` on [line 194](https://github.com/ONT-Avocados/python-template/blob/master/OEP5Sample/OEP5Sample_compiler2.0.py#L194) in both samples
